#+TITLE: Module 1 Notes

* Donald Judd - Masterpieces

** Author's intro

- 1960's Donald Judd argues that there has been a decline in the quality of new art.

- Blames decline due to ignorance of historical conditions and of the values of art.

- Argues need for 'virtually a whole civilization, new knowledge and attitudes' to oppose commerce.

** Paragraph 1 (p. 1140)

- The presence of good artists is exceedingly given by themselves

- Reforms, more money or a greater audience do not guarantee new artists

- The condition in which art is made is important

- Art doesn't tolerate frivolity and abuse

** Paragraph 3 (p. 1140)

- In the last ~200 years, society went from rural to industrial

- Most of society (descendants of peasants) needs to be educated,
  but there are not enough educated people to do this

- Population increased too much to the point where it was not sustainable to teach each person well; so only bare informationi was taught

  + Judd gives anecdote of lecture in Texas

  + "Presumably the next day they went to work and taught 4000 students less than that."

  + "This is the fundamental knowledge of society."

** Paragraph 4 (p. 1141)

- Education is the ultimate problem in the US (and Europe, but not as much)

** Paragraph 5 (p. 1141)

- Religion was no longer an advance in the understanding of humanity and of nature.

- "Before Bernini religion was the nature of the world and of man, and for the most part, despite corruption and suppression, its morality and cosmology opposed commerce and mundane power."

- "For a century there has been no counterforce to power and commerce, nothing to say that the existence of the individual and of the world, their relationship, that between individuals, and activities which signify these, such as art, are not a matter of business and are not to be bought and sold."

** Paragraph 6 (p. 1141)

- Art, architecture and music no longer had an institutional support.

- They could only make and sell and so live within the context of commerce.

** Paragraph 7 (p. 1141)

- Business is an essential basis, but it's not civilization itself.

- Business doesn't deserve the power and prestige surrounding it.

** Paragraph 8 (pp. 1141-1142)

- A new civilization to oppose commerce

  + Can't use one of the debased religions

  + Can't be an institution

  + Must be lost of diverse and educated people arguing and objecting

  + People must have real knowledge and judgment and they must have an influence upon the less educated majority

  + Art, architecture, music, and dance are close to being force underground; preventing opposition to commerce

- For a century, there usually have been two versions of art

  + One real, but poor and underground

  + One fake, but rich and conspicuous

** Paragraph 9 (p. 1142)

- New attitude towards art has been more democratic.

  + "It's not nice to say that my work is better than yours."

** Paragraph 10 (p. 1142)

- The guy in Tucson with the Spanish-Colonial TV set is the one who bulldozed the adobe houses in the old part of town.

** Paragraph 11 (p. 1142)
* Kristeller - Modern System of the Arts

- Aesthetics is comparatively new

- Irreducible nucleus of the modern system of the arts (the five "major arts"):

  1. Painting

  2. Sculpture

  3. Architecture

  4. Music

  5. Poetry

- Kristeller argues that this system of the five major arts underlies all modern aesthetics, is of recent origin and did not assume definite shape before the eighteenth century

- Ancient statements about Art and the arts have often been read and understood as if they were meant in the modern sense of fine arts.
  This may in some cases have led to fruitful errors, but it does not do justice to the original intention of the ancient writers. (p. 166)
